version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - 56000:56000
    networks:
      - agent_network

  playground:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 81:3000
    networks:
      - agent_network
networks:
  agent_network: