version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - 56000:56000
    networks:
      - agent_network

  playground:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 80:3000
    networks:
      - agent_network
      
  mongo:
    image: mongo:4.4.9
    container_name: mongo_service
    ports:
      - 27020:27017
    volumes:
      - ./db/data:/data/db
networks:
  agent_network: